package com.yejh.bean;

import javax.validation.constraints.Pattern;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.emp_id
     *
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.emp_name
     *
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    @Pattern(regexp = "(^[a-zA-Z0-9_]{3,10}$)|(^[\\u2E80-\\u9FFF]{2,5}$)",
            message = "用户名必须是3-10位字母下划线和数字的组合或者2-5位中文！")
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.gender
     *
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.email
     *
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    @Pattern(regexp = "^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$",
            message = "邮箱格式不正确！")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.d_id
     *
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    private Integer dId;

    private Department dept;

    public Employee(Integer empId, String empName, String gender, String email, Integer dId, Department dept) {
        this.empId = empId;
        this.empName = empName;
        this.gender = gender;
        this.email = email;
        this.dId = dId;
        this.dept = dept;
    }

    public Employee() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.emp_id
     *
     * @return the value of t_employee.emp_id
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.emp_id
     *
     * @param empId the value for t_employee.emp_id
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.emp_name
     *
     * @return the value of t_employee.emp_name
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.emp_name
     *
     * @param empName the value for t_employee.emp_name
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.gender
     *
     * @return the value of t_employee.gender
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.gender
     *
     * @param gender the value for t_employee.gender
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.email
     *
     * @return the value of t_employee.email
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.email
     *
     * @param email the value for t_employee.email
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.d_id
     *
     * @return the value of t_employee.d_id
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.d_id
     *
     * @param dId the value for t_employee.d_id
     * @mbg.generated Thu Dec 19 23:22:19 CST 2019
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    public Department getDept() {
        return dept;
    }

    public void setDept(Department dept) {
        this.dept = dept;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", dId=" + dId +
                ", dept=" + dept +
                '}';
    }
}